<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>MQS</string>
    <key>scopeName</key>
    <string>source.mqs</string>
    <key>fileTypes</key>
    <array>
      <string>mqs</string>
    </array>
    <key>firstLineMatch</key>
    <string>^#!/.*\bmqs\b</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#comment</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#namespace</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#declaration</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#expression</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#invalid</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>params</key>
      <dict>
        <key>begin</key>
        <string>\(</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.parameters.begin.mqs</string>
          </dict>
        </dict>
        <key>contentName</key>
        <string>meta.parameters.mqs</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>([A-Za-z_][A-Za-z_0-9]*'*)(?:\s*(:)\s*(?:(nat|int|flt)|(\S*)))?</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.parameter.mqs</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.type-annonation.mqs</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>storage.type.mqs</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>invalid.illegal.mqs</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>\,</string>
            <key>name</key>
            <string>punctuation.separator.parameters.mqs</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#invalid</string>
          </dict>
        </array>
        <key>end</key>
        <string>\)</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.parameters.end.mqs</string>
          </dict>
        </dict>
      </dict>
      <key>namespace</key>
      <dict>
        <key>begin</key>
        <string>([A-Za-z_][A-Za-z_0-9]*'*)\s*(\{)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.name.namespace.mqs</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.namespace.begin.mqs</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#expression</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#declaration</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#invalid</string>
          </dict>
        </array>
        <key>end</key>
        <string>\}</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.namespace.end.mqs</string>
          </dict>
        </dict>
      </dict>
      <key>declaration</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#import</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#theorem-decl</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#conclusion-decl</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#variable-decl</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#function-decl</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#question-decl</string>
          </dict>
        </array>
      </dict>
      <key>import</key>
      <dict>
        <key>match</key>
        <string>(#)\s*(?:((?:/|~|\.|))\s*(\/))?\s*(?:([A-Za-z_][A-Za-z_0-9]*'*)\s*(\/)\s*)*([A-Za-z_][A-Za-z_0-9]*'*)</string>
        <key>captures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>entity.name.namespace.mqs</string>
          </dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.import.mqs</string>
          </dict>
        </dict>
      </dict>
      <key>theorem-decl</key>
      <dict>
        <key>begin</key>
        <string>(!)\s*(?:([A-Za-z_][A-Za-z_0-9]*'*)|(\S*))\s*</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.declaration.theorem.mqs</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.function.theorem.mqs</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>invalid.illegal.mqs</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#params</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#invalid</string>
          </dict>
        </array>
        <key>end</key>
        <string>:=</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>keyword.definition.theorem.mqs</string>
          </dict>
        </dict>
      </dict>
      <key>conclusion-decl</key>
      <dict>
        <key>begin</key>
        <string>(&amp;)\s*(?:([A-Za-z_][A-Za-z_0-9]*'*)|(\S*))\s*</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.declaration.conclusion.mqs</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.function.conclusion.mqs</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>invalid.illegal.mqs</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#params</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#invalid</string>
          </dict>
        </array>
        <key>end</key>
        <string>(?:(t|f)|(\S*))\s*(:=)</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>constant.language.bool.mqs</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>invalid.illegal.mqs</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>keyword.definition.conclusion.mqs</string>
          </dict>
        </dict>
      </dict>
      <key>variable-decl</key>
      <dict>
        <key>match</key>
        <string>(\$)\s*(?:([A-Za-z_][A-Za-z_0-9]*'*)|(\S*))\s*(:=)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.declaration.variable.mqs</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.function.variable.mqs</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>invalid.illegal.mqs</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>keyword.definition.variable.mqs</string>
          </dict>
        </dict>
      </dict>
      <key>function-decl</key>
      <dict>
        <key>begin</key>
        <string>(@)\s*(?:([A-Za-z_][A-Za-z_0-9]*'*)|(\S*))\s*</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.declaration.function.mqs</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.function.function.mqs</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>invalid.illegal.mqs</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#params</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#invalid</string>
          </dict>
        </array>
        <key>end</key>
        <string>(?:\s*(:)\s*(?:(nat|int|flt)|(\S*)))?\s*(\:=)</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.type-annonation.mqs</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>storage.type.mqs</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>invalid.illegal.mqs</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>keyword.definition.function.mqs</string>
          </dict>
        </dict>
      </dict>
      <key>question-decl</key>
      <dict>
        <key>begin</key>
        <string>(\?)\s*(?:([A-Za-z_][A-Za-z_0-9]*'*)\s*)?</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.declaration.question.mqs</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.function.question.mqs</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#params</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#invalid</string>
          </dict>
        </array>
        <key>end</key>
        <string>:=</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>keyword.definition.question.mqs</string>
          </dict>
        </dict>
      </dict>
      <key>expression</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#operator</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#variable</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#number</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#variadic</string>
          </dict>
        </array>
      </dict>
      <key>operator</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>:=</string>
            <key>name</key>
            <string>keyword.definition.mqs</string>
          </dict>
          <dict>
            <key>match</key>
            <string>&lt;=&gt;</string>
            <key>name</key>
            <string>support.function.match.mqs</string>
          </dict>
          <dict>
            <key>match</key>
            <string>&lt;/=&gt;</string>
            <key>name</key>
            <string>support.function.not-match.mqs</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\%</string>
            <key>name</key>
            <string>support.function.divisible.mqs</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\=|/=</string>
            <key>name</key>
            <string>keyword.operator.comparison.mqs</string>
          </dict>
          <dict>
            <key>match</key>
            <string>&lt;=|&gt;=|&lt;&gt;|&lt;|&gt;</string>
            <key>name</key>
            <string>keyword.operator.relational.mqs</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\*|/|-|\+|\^</string>
            <key>name</key>
            <string>keyword.operator.arithmetic.mqs</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>\(</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.group.begin.mqs</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#expression</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#invalid</string>
              </dict>
            </array>
            <key>end</key>
            <string>\)</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.group.end.mqs</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>variable</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>([A-Za-z_][A-Za-z_0-9]*'*)\s*(\()</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.mqs</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.parentheses.arguments.start.mqs</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
              <dict>
                <key>match</key>
                <string>\,</string>
                <key>name</key>
                <string>punctuation.sequence.arguments.mqs</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#expression</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#invalid</string>
              </dict>
            </array>
            <key>end</key>
            <string>\)</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.parentheses.arguments.start.mqs</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>[A-Za-z_][A-Za-z_0-9]*'*</string>
            <key>scope</key>
            <string>variable.mqs</string>
          </dict>
        </array>
      </dict>
      <key>number</key>
      <dict>
        <key>match</key>
        <string>\b\b[0-9]+(?:\.[0-9]*)?\b|\b0b[0-1]+\b|\b0c[0-7]+\b|\b0x[0-9a-fA-F]+\b\b</string>
        <key>name</key>
        <string>constant.numeric.mqs</string>
      </dict>
      <key>variadic</key>
      <dict>
        <key>match</key>
        <string>\.\.(?:\b[0-9]+(?:\.[0-9]*)?\b|\b0b[0-1]+\b|\b0c[0-7]+\b|\b0x[0-9a-fA-F]+\b)?</string>
        <key>name</key>
        <string>support.variadic.mqs</string>
      </dict>
      <key>comment</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>comment.block.mqs</string>
            <key>begin</key>
            <string>--\*</string>
            <key>end</key>
            <string>\*--</string>
          </dict>
          <dict>
            <key>name</key>
            <string>comment.line.mqs</string>
            <key>match</key>
            <string>--.*$</string>
          </dict>
        </array>
      </dict>
      <key>invalid</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\s+</string>
          </dict>
          <dict>
            <key>name</key>
            <string>invalid.illegal.mqs</string>
            <key>match</key>
            <string>\S</string>
          </dict>
        </array>
      </dict>
    </dict>
  </dict>
</plist>