[package]
name = "mqs"
version = "0.1.0"
edition = "2021"
description = "The MQS Interpreter"

[dependencies]
clap = { version = "3.1.17", default-features = false, features = ["std", "suggestions", "derive", "env"] }
yansi = "0.5.1"
json = "0.12.4"